### ISSUE TITLE
[ALL] Create test repository with a current copy of a project

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/component-library#121]

**Comment by andrewrubin** [comment]
This is done. It's a pretty open-ended task tbh, so I've created a feature branch on there called `feature/component-library-testing`. Since corgi is constantly evolving, and also since it has multiple templates we use, I don't think it makes sense to have _one_ source of truth for what a project playground looks like. 

Repo: https://github.com/wethegit/project-playground

Demo testing ground: https://pr-1.d15k0q7rvrhtf2.amplifyapp.com/
